setup-poetry: Add `use-cache` input and regression tests (#8)
* github: Add tests for setup-python and setup-poetry

* github: Fix version parsing

* github: Add another job to combine test results for status checks

* setup-poetry: Add use-cache input and cache-hit output

* github: Add test for setup-poetry caching

* setup-poetry: Document new input and output

* github: Add a use_cache=false test

* github: Change conditional step names to reflect result of condition, not the check

diff --git a/.github/workflows/test_actions.yml b/.github/workflows/test_actions.yml
--- a/.github/workflows/test_actions.yml
+++ b/.github/workflows/test_actions.yml
@@ -5,6 +5,122 @@ on:
   workflow_dispatch:
 
 jobs:
+  test_setup_python:
+    name: Test setup-python
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [windows-latest, ubuntu-latest]
+        python-version: [3.9, '3.10', 3.11, 3.12, 3.13]
+    steps:
+      - name: Check out repo
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: Set up Python
+        uses: ./setup-python
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Check Python version
+        run: |
+          import sys
+          version = sys.version_info[:2]
+          expected_version = tuple(map(int, "${{ matrix.python-version }}".split(".")))
+          if version != expected_version:
+              print(f"::error title=Test Failure::The Python version does not match. Got {version}, expected {expected_version}.")
+              sys.exit(1)
+        shell: python
+
+  test_setup_poetry:
+    name: Test setup-poetry
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [windows-latest, ubuntu-latest]
+        python-version: [3.9, '3.10', 3.11, 3.12, 3.13]
+    steps:
+      - name: Check out repo
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: Set up Python
+        uses: ./setup-python
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Set up Poetry
+        uses: ./setup-poetry
+      - name: Create project
+        run: poetry new test-project
+      - name: Check that the project was created
+        run: |
+          if [ ! -f test-project/pyproject.toml ]; then
+            echo "::error title=Test Failure::The project file does not exist."
+            exit 1
+          fi
+        shell: bash
+
+  test_setup_poetry_cache_hit:
+    name: Test setup-poetry (cache hit)
+    runs-on: ${{ matrix.os }}
+    needs: test_setup_poetry
+    strategy:
+      matrix:
+        os: [windows-latest, ubuntu-latest]
+        python-version: [3.9, '3.10', 3.11, 3.12, 3.13]
+    steps:
+      - name: Check out repo
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: Set up Python
+        uses: ./setup-python
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Set up Poetry
+        id: setup-poetry
+        uses: ./setup-poetry
+      - name: Error if cache miss
+        if: steps.setup-poetry.outputs.cache-hit != 'true'
+        run: echo "::error title=Test Failure::Expected cache hit."; exit 1
+        shell: bash
+      - name: Create project
+        run: poetry new test-project
+      - name: Check that the project was created
+        run: |
+          if [ ! -f test-project/pyproject.toml ]; then
+            echo "::error title=Test Failure::The project file does not exist."
+            exit 1
+          fi
+        shell: bash
+  
+  test_setup_poetry_no_cache:
+    name: Test setup-poetry (no cache)
+    runs-on: ${{ matrix.os }}
+    needs: test_setup_poetry
+    strategy:
+      matrix:
+        os: [windows-latest, ubuntu-latest]
+        python-version: [3.9, '3.10', 3.11, 3.12, 3.13]
+    steps:
+      - name: Check out repo
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: Set up Python
+        uses: ./setup-python
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Set up Poetry
+        id: setup-poetry
+        uses: ./setup-poetry
+        with:
+          use-cache: false
+      - name: Error if cache hit
+        if: steps.setup-poetry.outputs.cache-hit == 'true'
+        run: echo "::error title=Test Failure::Expected cache miss."; exit 1
+        shell: bash
+      - name: Create project
+        run: poetry new test-project
+      - name: Check that the project was created
+        run: |
+          if [ ! -f test-project/pyproject.toml ]; then
+            echo "::error title=Test Failure::The project file does not exist."
+            exit 1
+          fi
+        shell: bash
+  
   test_check_project_version:
     name: Test check-project-version
     runs-on: ubuntu-latest
@@ -38,6 +154,7 @@ jobs:
         run: |
           echo "::error title=Test Failure::The previous step did not fail as expected."
           exit 1
+
   test_update_project_version:
     name: Test update-project-version
     runs-on: ubuntu-latest
@@ -84,3 +201,22 @@ jobs:
         with:
           project-directory: test-project
           expected-version: 1.0.2.dev1
+
+  # This job is intended to combine the test results so we don't have to list
+  # each matrix combination in the required status check settings. There are a
+  # lot of corner cases that make this harder than it should be; see See
+  # https://github.com/orgs/community/discussions/26822 for more info.
+  test_results:
+    name: Test Results
+    runs-on: ubuntu-latest
+    needs: [
+      test_setup_python, 
+      test_setup_poetry, 
+      test_setup_poetry_cache_hit,
+      test_setup_poetry_no_cache,
+      test_check_project_version,
+      test_update_project_version
+    ]
+    if: ${{ !cancelled() }}
+    steps:
+      - run: exit 0
